/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Politics247Generated;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-01-20")
public class CommentData implements org.apache.thrift.TBase<CommentData, CommentData._Fields>, java.io.Serializable, Cloneable, Comparable<CommentData>, android.os.Parcelable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CommentData");

  private static final org.apache.thrift.protocol.TField USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("userID", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField POST_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("postID", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField COMMENT_TEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("commentText", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CommentDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CommentDataTupleSchemeFactory());
  }

  public long userID; // required
  public long postID; // required
  public String commentText; // required

  @Override
  public void writeToParcel(android.os.Parcel out, int flags) {
    //primitive bitfield of type: byte
    out.writeByte(__isset_bitfield);

    out.writeLong(userID);
    out.writeLong(postID);
    out.writeString(commentText);
  }

  @Override
  public int describeContents() {
    return 0;
  }

  public CommentData(android.os.Parcel in) {
    //primitive bitfield of type: byte
    __isset_bitfield = in.readByte();

    this.userID = in.readLong();
    this.postID = in.readLong();
    this.commentText= in.readString();
  }

  public static final android.os.Parcelable.Creator<CommentData> CREATOR = new android.os.Parcelable.Creator<CommentData>() {
    @Override
    public CommentData[] newArray(int size) {
      return new CommentData[size];
    }

    @Override
    public CommentData createFromParcel(android.os.Parcel in) {
      return new CommentData(in);
    }
  };

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_ID((short)1, "userID"),
    POST_ID((short)2, "postID"),
    COMMENT_TEXT((short)3, "commentText");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_ID
          return USER_ID;
        case 2: // POST_ID
          return POST_ID;
        case 3: // COMMENT_TEXT
          return COMMENT_TEXT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __USERID_ISSET_ID = 0;
  private static final int __POSTID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_ID, new org.apache.thrift.meta_data.FieldMetaData("userID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.POST_ID, new org.apache.thrift.meta_data.FieldMetaData("postID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.COMMENT_TEXT, new org.apache.thrift.meta_data.FieldMetaData("commentText", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CommentData.class, metaDataMap);
  }

  public CommentData() {
  }

  public CommentData(
    long userID,
    long postID,
    String commentText)
  {
    this();
    this.userID = userID;
    setUserIDIsSet(true);
    this.postID = postID;
    setPostIDIsSet(true);
    this.commentText = commentText;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CommentData(CommentData other) {
    __isset_bitfield = other.__isset_bitfield;
    this.userID = other.userID;
    this.postID = other.postID;
    if (other.isSetCommentText()) {
      this.commentText = other.commentText;
    }
  }

  public CommentData deepCopy() {
    return new CommentData(this);
  }

  @Override
  public void clear() {
    setUserIDIsSet(false);
    this.userID = 0;
    setPostIDIsSet(false);
    this.postID = 0;
    this.commentText = null;
  }

  public long getUserID() {
    return this.userID;
  }

  public CommentData setUserID(long userID) {
    this.userID = userID;
    setUserIDIsSet(true);
    return this;
  }

  public void unsetUserID() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  /** Returns true if field userID is set (has been assigned a value) and false otherwise */
  public boolean isSetUserID() {
    return EncodingUtils.testBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  public void setUserIDIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __USERID_ISSET_ID, value);
  }

  public long getPostID() {
    return this.postID;
  }

  public CommentData setPostID(long postID) {
    this.postID = postID;
    setPostIDIsSet(true);
    return this;
  }

  public void unsetPostID() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __POSTID_ISSET_ID);
  }

  /** Returns true if field postID is set (has been assigned a value) and false otherwise */
  public boolean isSetPostID() {
    return EncodingUtils.testBit(__isset_bitfield, __POSTID_ISSET_ID);
  }

  public void setPostIDIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __POSTID_ISSET_ID, value);
  }

  public String getCommentText() {
    return this.commentText;
  }

  public CommentData setCommentText(String commentText) {
    this.commentText = commentText;
    return this;
  }

  public void unsetCommentText() {
    this.commentText = null;
  }

  /** Returns true if field commentText is set (has been assigned a value) and false otherwise */
  public boolean isSetCommentText() {
    return this.commentText != null;
  }

  public void setCommentTextIsSet(boolean value) {
    if (!value) {
      this.commentText = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case USER_ID:
      if (value == null) {
        unsetUserID();
      } else {
        setUserID((Long)value);
      }
      break;

    case POST_ID:
      if (value == null) {
        unsetPostID();
      } else {
        setPostID((Long)value);
      }
      break;

    case COMMENT_TEXT:
      if (value == null) {
        unsetCommentText();
      } else {
        setCommentText((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case USER_ID:
      return getUserID();

    case POST_ID:
      return getPostID();

    case COMMENT_TEXT:
      return getCommentText();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case USER_ID:
      return isSetUserID();
    case POST_ID:
      return isSetPostID();
    case COMMENT_TEXT:
      return isSetCommentText();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CommentData)
      return this.equals((CommentData)that);
    return false;
  }

  public boolean equals(CommentData that) {
    if (that == null)
      return false;

    boolean this_present_userID = true;
    boolean that_present_userID = true;
    if (this_present_userID || that_present_userID) {
      if (!(this_present_userID && that_present_userID))
        return false;
      if (this.userID != that.userID)
        return false;
    }

    boolean this_present_postID = true;
    boolean that_present_postID = true;
    if (this_present_postID || that_present_postID) {
      if (!(this_present_postID && that_present_postID))
        return false;
      if (this.postID != that.postID)
        return false;
    }

    boolean this_present_commentText = true && this.isSetCommentText();
    boolean that_present_commentText = true && that.isSetCommentText();
    if (this_present_commentText || that_present_commentText) {
      if (!(this_present_commentText && that_present_commentText))
        return false;
      if (!this.commentText.equals(that.commentText))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_userID = true;
    list.add(present_userID);
    if (present_userID)
      list.add(userID);

    boolean present_postID = true;
    list.add(present_postID);
    if (present_postID)
      list.add(postID);

    boolean present_commentText = true && (isSetCommentText());
    list.add(present_commentText);
    if (present_commentText)
      list.add(commentText);

    return list.hashCode();
  }

  @Override
  public int compareTo(CommentData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUserID()).compareTo(other.isSetUserID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userID, other.userID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPostID()).compareTo(other.isSetPostID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPostID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.postID, other.postID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCommentText()).compareTo(other.isSetCommentText());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCommentText()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.commentText, other.commentText);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CommentData(");
    boolean first = true;

    sb.append("userID:");
    sb.append(this.userID);
    first = false;
    if (!first) sb.append(", ");
    sb.append("postID:");
    sb.append(this.postID);
    first = false;
    if (!first) sb.append(", ");
    sb.append("commentText:");
    if (this.commentText == null) {
      sb.append("null");
    } else {
      sb.append(this.commentText);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CommentDataStandardSchemeFactory implements SchemeFactory {
    public CommentDataStandardScheme getScheme() {
      return new CommentDataStandardScheme();
    }
  }

  private static class CommentDataStandardScheme extends StandardScheme<CommentData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CommentData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.userID = iprot.readI64();
              struct.setUserIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // POST_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.postID = iprot.readI64();
              struct.setPostIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // COMMENT_TEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.commentText = iprot.readString();
              struct.setCommentTextIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CommentData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(USER_ID_FIELD_DESC);
      oprot.writeI64(struct.userID);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(POST_ID_FIELD_DESC);
      oprot.writeI64(struct.postID);
      oprot.writeFieldEnd();
      if (struct.commentText != null) {
        oprot.writeFieldBegin(COMMENT_TEXT_FIELD_DESC);
        oprot.writeString(struct.commentText);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CommentDataTupleSchemeFactory implements SchemeFactory {
    public CommentDataTupleScheme getScheme() {
      return new CommentDataTupleScheme();
    }
  }

  private static class CommentDataTupleScheme extends TupleScheme<CommentData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CommentData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetUserID()) {
        optionals.set(0);
      }
      if (struct.isSetPostID()) {
        optionals.set(1);
      }
      if (struct.isSetCommentText()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetUserID()) {
        oprot.writeI64(struct.userID);
      }
      if (struct.isSetPostID()) {
        oprot.writeI64(struct.postID);
      }
      if (struct.isSetCommentText()) {
        oprot.writeString(struct.commentText);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CommentData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.userID = iprot.readI64();
        struct.setUserIDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.postID = iprot.readI64();
        struct.setPostIDIsSet(true);
      }
      if (incoming.get(2)) {
        struct.commentText = iprot.readString();
        struct.setCommentTextIsSet(true);
      }
    }
  }

}

