/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Politics247Generated;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-01-20")
public class RateData implements org.apache.thrift.TBase<RateData, RateData._Fields>, java.io.Serializable, Cloneable, Comparable<RateData>, android.os.Parcelable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RateData");

  private static final org.apache.thrift.protocol.TField USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("userID", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField POST_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("postID", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField RATING_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("ratingValue", org.apache.thrift.protocol.TType.DOUBLE, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RateDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RateDataTupleSchemeFactory());
  }

  public long userID; // required
  public long postID; // required
  public double ratingValue; // required

  @Override
  public void writeToParcel(android.os.Parcel out, int flags) {
    //primitive bitfield of type: byte
    out.writeByte(__isset_bitfield);

    out.writeLong(userID);
    out.writeLong(postID);
    out.writeDouble(ratingValue);
  }

  @Override
  public int describeContents() {
    return 0;
  }

  public RateData(android.os.Parcel in) {
    //primitive bitfield of type: byte
    __isset_bitfield = in.readByte();

    this.userID = in.readLong();
    this.postID = in.readLong();
    this.ratingValue = in.readDouble();
  }

  public static final android.os.Parcelable.Creator<RateData> CREATOR = new android.os.Parcelable.Creator<RateData>() {
    @Override
    public RateData[] newArray(int size) {
      return new RateData[size];
    }

    @Override
    public RateData createFromParcel(android.os.Parcel in) {
      return new RateData(in);
    }
  };

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_ID((short)1, "userID"),
    POST_ID((short)2, "postID"),
    RATING_VALUE((short)3, "ratingValue");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_ID
          return USER_ID;
        case 2: // POST_ID
          return POST_ID;
        case 3: // RATING_VALUE
          return RATING_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __USERID_ISSET_ID = 0;
  private static final int __POSTID_ISSET_ID = 1;
  private static final int __RATINGVALUE_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_ID, new org.apache.thrift.meta_data.FieldMetaData("userID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.POST_ID, new org.apache.thrift.meta_data.FieldMetaData("postID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.RATING_VALUE, new org.apache.thrift.meta_data.FieldMetaData("ratingValue", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RateData.class, metaDataMap);
  }

  public RateData() {
  }

  public RateData(
    long userID,
    long postID,
    double ratingValue)
  {
    this();
    this.userID = userID;
    setUserIDIsSet(true);
    this.postID = postID;
    setPostIDIsSet(true);
    this.ratingValue = ratingValue;
    setRatingValueIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RateData(RateData other) {
    __isset_bitfield = other.__isset_bitfield;
    this.userID = other.userID;
    this.postID = other.postID;
    this.ratingValue = other.ratingValue;
  }

  public RateData deepCopy() {
    return new RateData(this);
  }

  @Override
  public void clear() {
    setUserIDIsSet(false);
    this.userID = 0;
    setPostIDIsSet(false);
    this.postID = 0;
    setRatingValueIsSet(false);
    this.ratingValue = 0.0;
  }

  public long getUserID() {
    return this.userID;
  }

  public RateData setUserID(long userID) {
    this.userID = userID;
    setUserIDIsSet(true);
    return this;
  }

  public void unsetUserID() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  /** Returns true if field userID is set (has been assigned a value) and false otherwise */
  public boolean isSetUserID() {
    return EncodingUtils.testBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  public void setUserIDIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __USERID_ISSET_ID, value);
  }

  public long getPostID() {
    return this.postID;
  }

  public RateData setPostID(long postID) {
    this.postID = postID;
    setPostIDIsSet(true);
    return this;
  }

  public void unsetPostID() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __POSTID_ISSET_ID);
  }

  /** Returns true if field postID is set (has been assigned a value) and false otherwise */
  public boolean isSetPostID() {
    return EncodingUtils.testBit(__isset_bitfield, __POSTID_ISSET_ID);
  }

  public void setPostIDIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __POSTID_ISSET_ID, value);
  }

  public double getRatingValue() {
    return this.ratingValue;
  }

  public RateData setRatingValue(double ratingValue) {
    this.ratingValue = ratingValue;
    setRatingValueIsSet(true);
    return this;
  }

  public void unsetRatingValue() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __RATINGVALUE_ISSET_ID);
  }

  /** Returns true if field ratingValue is set (has been assigned a value) and false otherwise */
  public boolean isSetRatingValue() {
    return EncodingUtils.testBit(__isset_bitfield, __RATINGVALUE_ISSET_ID);
  }

  public void setRatingValueIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __RATINGVALUE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case USER_ID:
      if (value == null) {
        unsetUserID();
      } else {
        setUserID((Long)value);
      }
      break;

    case POST_ID:
      if (value == null) {
        unsetPostID();
      } else {
        setPostID((Long)value);
      }
      break;

    case RATING_VALUE:
      if (value == null) {
        unsetRatingValue();
      } else {
        setRatingValue((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case USER_ID:
      return getUserID();

    case POST_ID:
      return getPostID();

    case RATING_VALUE:
      return getRatingValue();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case USER_ID:
      return isSetUserID();
    case POST_ID:
      return isSetPostID();
    case RATING_VALUE:
      return isSetRatingValue();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RateData)
      return this.equals((RateData)that);
    return false;
  }

  public boolean equals(RateData that) {
    if (that == null)
      return false;

    boolean this_present_userID = true;
    boolean that_present_userID = true;
    if (this_present_userID || that_present_userID) {
      if (!(this_present_userID && that_present_userID))
        return false;
      if (this.userID != that.userID)
        return false;
    }

    boolean this_present_postID = true;
    boolean that_present_postID = true;
    if (this_present_postID || that_present_postID) {
      if (!(this_present_postID && that_present_postID))
        return false;
      if (this.postID != that.postID)
        return false;
    }

    boolean this_present_ratingValue = true;
    boolean that_present_ratingValue = true;
    if (this_present_ratingValue || that_present_ratingValue) {
      if (!(this_present_ratingValue && that_present_ratingValue))
        return false;
      if (this.ratingValue != that.ratingValue)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_userID = true;
    list.add(present_userID);
    if (present_userID)
      list.add(userID);

    boolean present_postID = true;
    list.add(present_postID);
    if (present_postID)
      list.add(postID);

    boolean present_ratingValue = true;
    list.add(present_ratingValue);
    if (present_ratingValue)
      list.add(ratingValue);

    return list.hashCode();
  }

  @Override
  public int compareTo(RateData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUserID()).compareTo(other.isSetUserID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userID, other.userID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPostID()).compareTo(other.isSetPostID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPostID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.postID, other.postID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRatingValue()).compareTo(other.isSetRatingValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRatingValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ratingValue, other.ratingValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RateData(");
    boolean first = true;

    sb.append("userID:");
    sb.append(this.userID);
    first = false;
    if (!first) sb.append(", ");
    sb.append("postID:");
    sb.append(this.postID);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ratingValue:");
    sb.append(this.ratingValue);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RateDataStandardSchemeFactory implements SchemeFactory {
    public RateDataStandardScheme getScheme() {
      return new RateDataStandardScheme();
    }
  }

  private static class RateDataStandardScheme extends StandardScheme<RateData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RateData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.userID = iprot.readI64();
              struct.setUserIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // POST_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.postID = iprot.readI64();
              struct.setPostIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // RATING_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.ratingValue = iprot.readDouble();
              struct.setRatingValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RateData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(USER_ID_FIELD_DESC);
      oprot.writeI64(struct.userID);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(POST_ID_FIELD_DESC);
      oprot.writeI64(struct.postID);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RATING_VALUE_FIELD_DESC);
      oprot.writeDouble(struct.ratingValue);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RateDataTupleSchemeFactory implements SchemeFactory {
    public RateDataTupleScheme getScheme() {
      return new RateDataTupleScheme();
    }
  }

  private static class RateDataTupleScheme extends TupleScheme<RateData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RateData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetUserID()) {
        optionals.set(0);
      }
      if (struct.isSetPostID()) {
        optionals.set(1);
      }
      if (struct.isSetRatingValue()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetUserID()) {
        oprot.writeI64(struct.userID);
      }
      if (struct.isSetPostID()) {
        oprot.writeI64(struct.postID);
      }
      if (struct.isSetRatingValue()) {
        oprot.writeDouble(struct.ratingValue);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RateData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.userID = iprot.readI64();
        struct.setUserIDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.postID = iprot.readI64();
        struct.setPostIDIsSet(true);
      }
      if (incoming.get(2)) {
        struct.ratingValue = iprot.readDouble();
        struct.setRatingValueIsSet(true);
      }
    }
  }

}

