/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Politics247Generated;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-01-26")
public class SubscriptionData implements org.apache.thrift.TBase<SubscriptionData, SubscriptionData._Fields>, java.io.Serializable, Cloneable, Comparable<SubscriptionData>, android.os.Parcelable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SubscriptionData");

  private static final org.apache.thrift.protocol.TField SUBSCRIBER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("subscriberID", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField SUBSCRIPTION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("subscriptionID", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SubscriptionDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SubscriptionDataTupleSchemeFactory());
  }

  public long subscriberID; // required
  public long subscriptionID; // required

  @Override
  public void writeToParcel(android.os.Parcel out, int flags) {
    //primitive bitfield of type: byte
    out.writeByte(__isset_bitfield);

    out.writeLong(subscriberID);
    out.writeLong(subscriptionID);
  }

  @Override
  public int describeContents() {
    return 0;
  }

  public SubscriptionData(android.os.Parcel in) {
    //primitive bitfield of type: byte
    __isset_bitfield = in.readByte();

    this.subscriberID = in.readLong();
    this.subscriptionID = in.readLong();
  }

  public static final android.os.Parcelable.Creator<SubscriptionData> CREATOR = new android.os.Parcelable.Creator<SubscriptionData>() {
    @Override
    public SubscriptionData[] newArray(int size) {
      return new SubscriptionData[size];
    }

    @Override
    public SubscriptionData createFromParcel(android.os.Parcel in) {
      return new SubscriptionData(in);
    }
  };

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SUBSCRIBER_ID((short)1, "subscriberID"),
    SUBSCRIPTION_ID((short)2, "subscriptionID");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SUBSCRIBER_ID
          return SUBSCRIBER_ID;
        case 2: // SUBSCRIPTION_ID
          return SUBSCRIPTION_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SUBSCRIBERID_ISSET_ID = 0;
  private static final int __SUBSCRIPTIONID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SUBSCRIBER_ID, new org.apache.thrift.meta_data.FieldMetaData("subscriberID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.SUBSCRIPTION_ID, new org.apache.thrift.meta_data.FieldMetaData("subscriptionID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SubscriptionData.class, metaDataMap);
  }

  public SubscriptionData() {
  }

  public SubscriptionData(
    long subscriberID,
    long subscriptionID)
  {
    this();
    this.subscriberID = subscriberID;
    setSubscriberIDIsSet(true);
    this.subscriptionID = subscriptionID;
    setSubscriptionIDIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SubscriptionData(SubscriptionData other) {
    __isset_bitfield = other.__isset_bitfield;
    this.subscriberID = other.subscriberID;
    this.subscriptionID = other.subscriptionID;
  }

  public SubscriptionData deepCopy() {
    return new SubscriptionData(this);
  }

  @Override
  public void clear() {
    setSubscriberIDIsSet(false);
    this.subscriberID = 0;
    setSubscriptionIDIsSet(false);
    this.subscriptionID = 0;
  }

  public long getSubscriberID() {
    return this.subscriberID;
  }

  public SubscriptionData setSubscriberID(long subscriberID) {
    this.subscriberID = subscriberID;
    setSubscriberIDIsSet(true);
    return this;
  }

  public void unsetSubscriberID() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SUBSCRIBERID_ISSET_ID);
  }

  /** Returns true if field subscriberID is set (has been assigned a value) and false otherwise */
  public boolean isSetSubscriberID() {
    return EncodingUtils.testBit(__isset_bitfield, __SUBSCRIBERID_ISSET_ID);
  }

  public void setSubscriberIDIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SUBSCRIBERID_ISSET_ID, value);
  }

  public long getSubscriptionID() {
    return this.subscriptionID;
  }

  public SubscriptionData setSubscriptionID(long subscriptionID) {
    this.subscriptionID = subscriptionID;
    setSubscriptionIDIsSet(true);
    return this;
  }

  public void unsetSubscriptionID() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SUBSCRIPTIONID_ISSET_ID);
  }

  /** Returns true if field subscriptionID is set (has been assigned a value) and false otherwise */
  public boolean isSetSubscriptionID() {
    return EncodingUtils.testBit(__isset_bitfield, __SUBSCRIPTIONID_ISSET_ID);
  }

  public void setSubscriptionIDIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SUBSCRIPTIONID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SUBSCRIBER_ID:
      if (value == null) {
        unsetSubscriberID();
      } else {
        setSubscriberID((Long)value);
      }
      break;

    case SUBSCRIPTION_ID:
      if (value == null) {
        unsetSubscriptionID();
      } else {
        setSubscriptionID((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SUBSCRIBER_ID:
      return getSubscriberID();

    case SUBSCRIPTION_ID:
      return getSubscriptionID();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SUBSCRIBER_ID:
      return isSetSubscriberID();
    case SUBSCRIPTION_ID:
      return isSetSubscriptionID();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SubscriptionData)
      return this.equals((SubscriptionData)that);
    return false;
  }

  public boolean equals(SubscriptionData that) {
    if (that == null)
      return false;

    boolean this_present_subscriberID = true;
    boolean that_present_subscriberID = true;
    if (this_present_subscriberID || that_present_subscriberID) {
      if (!(this_present_subscriberID && that_present_subscriberID))
        return false;
      if (this.subscriberID != that.subscriberID)
        return false;
    }

    boolean this_present_subscriptionID = true;
    boolean that_present_subscriptionID = true;
    if (this_present_subscriptionID || that_present_subscriptionID) {
      if (!(this_present_subscriptionID && that_present_subscriptionID))
        return false;
      if (this.subscriptionID != that.subscriptionID)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_subscriberID = true;
    list.add(present_subscriberID);
    if (present_subscriberID)
      list.add(subscriberID);

    boolean present_subscriptionID = true;
    list.add(present_subscriptionID);
    if (present_subscriptionID)
      list.add(subscriptionID);

    return list.hashCode();
  }

  @Override
  public int compareTo(SubscriptionData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetSubscriberID()).compareTo(other.isSetSubscriberID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSubscriberID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.subscriberID, other.subscriberID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSubscriptionID()).compareTo(other.isSetSubscriptionID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSubscriptionID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.subscriptionID, other.subscriptionID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SubscriptionData(");
    boolean first = true;

    sb.append("subscriberID:");
    sb.append(this.subscriberID);
    first = false;
    if (!first) sb.append(", ");
    sb.append("subscriptionID:");
    sb.append(this.subscriptionID);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SubscriptionDataStandardSchemeFactory implements SchemeFactory {
    public SubscriptionDataStandardScheme getScheme() {
      return new SubscriptionDataStandardScheme();
    }
  }

  private static class SubscriptionDataStandardScheme extends StandardScheme<SubscriptionData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SubscriptionData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SUBSCRIBER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.subscriberID = iprot.readI64();
              struct.setSubscriberIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SUBSCRIPTION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.subscriptionID = iprot.readI64();
              struct.setSubscriptionIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SubscriptionData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SUBSCRIBER_ID_FIELD_DESC);
      oprot.writeI64(struct.subscriberID);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SUBSCRIPTION_ID_FIELD_DESC);
      oprot.writeI64(struct.subscriptionID);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SubscriptionDataTupleSchemeFactory implements SchemeFactory {
    public SubscriptionDataTupleScheme getScheme() {
      return new SubscriptionDataTupleScheme();
    }
  }

  private static class SubscriptionDataTupleScheme extends TupleScheme<SubscriptionData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SubscriptionData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSubscriberID()) {
        optionals.set(0);
      }
      if (struct.isSetSubscriptionID()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetSubscriberID()) {
        oprot.writeI64(struct.subscriberID);
      }
      if (struct.isSetSubscriptionID()) {
        oprot.writeI64(struct.subscriptionID);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SubscriptionData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.subscriberID = iprot.readI64();
        struct.setSubscriberIDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.subscriptionID = iprot.readI64();
        struct.setSubscriptionIDIsSet(true);
      }
    }
  }

}

