/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Politics247Generated;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ThriftUserType implements org.apache.thrift.TEnum {
  Normal(0),
  Political(1),
  Media(2);

  private final int value;

  private ThriftUserType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ThriftUserType findByValue(int value) { 
    switch (value) {
      case 0:
        return Normal;
      case 1:
        return Political;
      case 2:
        return Media;
      default:
        return null;
    }
  }
}
