/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Politics247Generated;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-01-24")
public class UserProfileResult implements org.apache.thrift.TBase<UserProfileResult, UserProfileResult._Fields>, java.io.Serializable, Cloneable, Comparable<UserProfileResult>, android.os.Parcelable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserProfileResult");

  private static final org.apache.thrift.protocol.TField IS_USER_PROFILE_VALID_FIELD_DESC = new org.apache.thrift.protocol.TField("isUserProfileValid", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField FIRST_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("firstName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField LAST_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("lastName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField LAST_NAME_PREFIX_FIELD_DESC = new org.apache.thrift.protocol.TField("lastNamePrefix", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField GENDER_FIELD_DESC = new org.apache.thrift.protocol.TField("gender", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField NATIONALITY_FIELD_DESC = new org.apache.thrift.protocol.TField("nationality", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField TOWN_FIELD_DESC = new org.apache.thrift.protocol.TField("town", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField DATE_OF_BIRTH_FIELD_DESC = new org.apache.thrift.protocol.TField("dateOfBirth", org.apache.thrift.protocol.TType.STRUCT, (short)8);
  private static final org.apache.thrift.protocol.TField POLITICAL_PREFERENCE_FIELD_DESC = new org.apache.thrift.protocol.TField("politicalPreference", org.apache.thrift.protocol.TType.STRING, (short)9);
  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)10);
  private static final org.apache.thrift.protocol.TField PARTY_FIELD_DESC = new org.apache.thrift.protocol.TField("party", org.apache.thrift.protocol.TType.STRING, (short)11);
  private static final org.apache.thrift.protocol.TField MEDIA_FIELD_DESC = new org.apache.thrift.protocol.TField("media", org.apache.thrift.protocol.TType.STRING, (short)12);
  private static final org.apache.thrift.protocol.TField USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("userId", org.apache.thrift.protocol.TType.I32, (short)13);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new UserProfileResultStandardSchemeFactory());
    schemes.put(TupleScheme.class, new UserProfileResultTupleSchemeFactory());
  }

  public boolean isUserProfileValid; // required
  public String firstName; // required
  public String lastName; // required
  public String lastNamePrefix; // required
  /**
   * 
   * @see Politics247Generated.ThriftGender
   */
  public Politics247Generated.ThriftGender gender; // required
  public String nationality; // required
  public String town; // required
  public Politics247Generated.ThriftDate dateOfBirth; // required
  public String politicalPreference; // required
  /**
   * 
   * @see Politics247Generated.ThriftUserType
   */
  public Politics247Generated.ThriftUserType type; // required
  public String party; // required
  public String media; // required
  public int userId; // required

  @Override
  public void writeToParcel(android.os.Parcel out, int flags) {
    //primitive bitfield of type: byte
    out.writeByte(__isset_bitfield);

    out.writeInt(isUserProfileValid ? 1 : 0);
    out.writeString(firstName);
    out.writeString(lastName);
    out.writeString(lastNamePrefix);
    out.writeInt(gender.getValue());
    out.writeString(nationality);
    out.writeString(town);
    out.writeParcelable(dateOfBirth, flags);
    out.writeString(politicalPreference);
    out.writeInt(type.getValue());
    out.writeString(party);
    out.writeString(media);
    out.writeInt(userId);
  }

  @Override
  public int describeContents() {
    return 0;
  }

  public UserProfileResult(android.os.Parcel in) {
    //primitive bitfield of type: byte
    __isset_bitfield = in.readByte();

    this.isUserProfileValid = (in.readInt()==1);
    this.firstName= in.readString();
    this.lastName= in.readString();
    this.lastNamePrefix= in.readString();
    this.gender = Politics247Generated.ThriftGender.findByValue(in.readInt());
    this.nationality= in.readString();
    this.town= in.readString();
    this.dateOfBirth= in.readParcelable(UserProfileResult.class.getClassLoader());
    this.politicalPreference= in.readString();
    this.type = Politics247Generated.ThriftUserType.findByValue(in.readInt());
    this.party= in.readString();
    this.media= in.readString();
    this.userId = in.readInt();
  }

  public static final android.os.Parcelable.Creator<UserProfileResult> CREATOR = new android.os.Parcelable.Creator<UserProfileResult>() {
    @Override
    public UserProfileResult[] newArray(int size) {
      return new UserProfileResult[size];
    }

    @Override
    public UserProfileResult createFromParcel(android.os.Parcel in) {
      return new UserProfileResult(in);
    }
  };

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IS_USER_PROFILE_VALID((short)1, "isUserProfileValid"),
    FIRST_NAME((short)2, "firstName"),
    LAST_NAME((short)3, "lastName"),
    LAST_NAME_PREFIX((short)4, "lastNamePrefix"),
    /**
     * 
     * @see Politics247Generated.ThriftGender
     */
    GENDER((short)5, "gender"),
    NATIONALITY((short)6, "nationality"),
    TOWN((short)7, "town"),
    DATE_OF_BIRTH((short)8, "dateOfBirth"),
    POLITICAL_PREFERENCE((short)9, "politicalPreference"),
    /**
     * 
     * @see Politics247Generated.ThriftUserType
     */
    TYPE((short)10, "type"),
    PARTY((short)11, "party"),
    MEDIA((short)12, "media"),
    USER_ID((short)13, "userId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IS_USER_PROFILE_VALID
          return IS_USER_PROFILE_VALID;
        case 2: // FIRST_NAME
          return FIRST_NAME;
        case 3: // LAST_NAME
          return LAST_NAME;
        case 4: // LAST_NAME_PREFIX
          return LAST_NAME_PREFIX;
        case 5: // GENDER
          return GENDER;
        case 6: // NATIONALITY
          return NATIONALITY;
        case 7: // TOWN
          return TOWN;
        case 8: // DATE_OF_BIRTH
          return DATE_OF_BIRTH;
        case 9: // POLITICAL_PREFERENCE
          return POLITICAL_PREFERENCE;
        case 10: // TYPE
          return TYPE;
        case 11: // PARTY
          return PARTY;
        case 12: // MEDIA
          return MEDIA;
        case 13: // USER_ID
          return USER_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ISUSERPROFILEVALID_ISSET_ID = 0;
  private static final int __USERID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IS_USER_PROFILE_VALID, new org.apache.thrift.meta_data.FieldMetaData("isUserProfileValid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.FIRST_NAME, new org.apache.thrift.meta_data.FieldMetaData("firstName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LAST_NAME, new org.apache.thrift.meta_data.FieldMetaData("lastName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LAST_NAME_PREFIX, new org.apache.thrift.meta_data.FieldMetaData("lastNamePrefix", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.GENDER, new org.apache.thrift.meta_data.FieldMetaData("gender", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, Politics247Generated.ThriftGender.class)));
    tmpMap.put(_Fields.NATIONALITY, new org.apache.thrift.meta_data.FieldMetaData("nationality", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TOWN, new org.apache.thrift.meta_data.FieldMetaData("town", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DATE_OF_BIRTH, new org.apache.thrift.meta_data.FieldMetaData("dateOfBirth", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Politics247Generated.ThriftDate.class)));
    tmpMap.put(_Fields.POLITICAL_PREFERENCE, new org.apache.thrift.meta_data.FieldMetaData("politicalPreference", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, Politics247Generated.ThriftUserType.class)));
    tmpMap.put(_Fields.PARTY, new org.apache.thrift.meta_data.FieldMetaData("party", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MEDIA, new org.apache.thrift.meta_data.FieldMetaData("media", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USER_ID, new org.apache.thrift.meta_data.FieldMetaData("userId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserProfileResult.class, metaDataMap);
  }

  public UserProfileResult() {
  }

  public UserProfileResult(
    boolean isUserProfileValid,
    String firstName,
    String lastName,
    String lastNamePrefix,
    Politics247Generated.ThriftGender gender,
    String nationality,
    String town,
    Politics247Generated.ThriftDate dateOfBirth,
    String politicalPreference,
    Politics247Generated.ThriftUserType type,
    String party,
    String media,
    int userId)
  {
    this();
    this.isUserProfileValid = isUserProfileValid;
    setIsUserProfileValidIsSet(true);
    this.firstName = firstName;
    this.lastName = lastName;
    this.lastNamePrefix = lastNamePrefix;
    this.gender = gender;
    this.nationality = nationality;
    this.town = town;
    this.dateOfBirth = dateOfBirth;
    this.politicalPreference = politicalPreference;
    this.type = type;
    this.party = party;
    this.media = media;
    this.userId = userId;
    setUserIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserProfileResult(UserProfileResult other) {
    __isset_bitfield = other.__isset_bitfield;
    this.isUserProfileValid = other.isUserProfileValid;
    if (other.isSetFirstName()) {
      this.firstName = other.firstName;
    }
    if (other.isSetLastName()) {
      this.lastName = other.lastName;
    }
    if (other.isSetLastNamePrefix()) {
      this.lastNamePrefix = other.lastNamePrefix;
    }
    if (other.isSetGender()) {
      this.gender = other.gender;
    }
    if (other.isSetNationality()) {
      this.nationality = other.nationality;
    }
    if (other.isSetTown()) {
      this.town = other.town;
    }
    if (other.isSetDateOfBirth()) {
      this.dateOfBirth = new Politics247Generated.ThriftDate(other.dateOfBirth);
    }
    if (other.isSetPoliticalPreference()) {
      this.politicalPreference = other.politicalPreference;
    }
    if (other.isSetType()) {
      this.type = other.type;
    }
    if (other.isSetParty()) {
      this.party = other.party;
    }
    if (other.isSetMedia()) {
      this.media = other.media;
    }
    this.userId = other.userId;
  }

  public UserProfileResult deepCopy() {
    return new UserProfileResult(this);
  }

  @Override
  public void clear() {
    setIsUserProfileValidIsSet(false);
    this.isUserProfileValid = false;
    this.firstName = null;
    this.lastName = null;
    this.lastNamePrefix = null;
    this.gender = null;
    this.nationality = null;
    this.town = null;
    this.dateOfBirth = null;
    this.politicalPreference = null;
    this.type = null;
    this.party = null;
    this.media = null;
    setUserIdIsSet(false);
    this.userId = 0;
  }

  public boolean isIsUserProfileValid() {
    return this.isUserProfileValid;
  }

  public UserProfileResult setIsUserProfileValid(boolean isUserProfileValid) {
    this.isUserProfileValid = isUserProfileValid;
    setIsUserProfileValidIsSet(true);
    return this;
  }

  public void unsetIsUserProfileValid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ISUSERPROFILEVALID_ISSET_ID);
  }

  /** Returns true if field isUserProfileValid is set (has been assigned a value) and false otherwise */
  public boolean isSetIsUserProfileValid() {
    return EncodingUtils.testBit(__isset_bitfield, __ISUSERPROFILEVALID_ISSET_ID);
  }

  public void setIsUserProfileValidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ISUSERPROFILEVALID_ISSET_ID, value);
  }

  public String getFirstName() {
    return this.firstName;
  }

  public UserProfileResult setFirstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

  public void unsetFirstName() {
    this.firstName = null;
  }

  /** Returns true if field firstName is set (has been assigned a value) and false otherwise */
  public boolean isSetFirstName() {
    return this.firstName != null;
  }

  public void setFirstNameIsSet(boolean value) {
    if (!value) {
      this.firstName = null;
    }
  }

  public String getLastName() {
    return this.lastName;
  }

  public UserProfileResult setLastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

  public void unsetLastName() {
    this.lastName = null;
  }

  /** Returns true if field lastName is set (has been assigned a value) and false otherwise */
  public boolean isSetLastName() {
    return this.lastName != null;
  }

  public void setLastNameIsSet(boolean value) {
    if (!value) {
      this.lastName = null;
    }
  }

  public String getLastNamePrefix() {
    return this.lastNamePrefix;
  }

  public UserProfileResult setLastNamePrefix(String lastNamePrefix) {
    this.lastNamePrefix = lastNamePrefix;
    return this;
  }

  public void unsetLastNamePrefix() {
    this.lastNamePrefix = null;
  }

  /** Returns true if field lastNamePrefix is set (has been assigned a value) and false otherwise */
  public boolean isSetLastNamePrefix() {
    return this.lastNamePrefix != null;
  }

  public void setLastNamePrefixIsSet(boolean value) {
    if (!value) {
      this.lastNamePrefix = null;
    }
  }

  /**
   * 
   * @see Politics247Generated.ThriftGender
   */
  public Politics247Generated.ThriftGender getGender() {
    return this.gender;
  }

  /**
   * 
   * @see Politics247Generated.ThriftGender
   */
  public UserProfileResult setGender(Politics247Generated.ThriftGender gender) {
    this.gender = gender;
    return this;
  }

  public void unsetGender() {
    this.gender = null;
  }

  /** Returns true if field gender is set (has been assigned a value) and false otherwise */
  public boolean isSetGender() {
    return this.gender != null;
  }

  public void setGenderIsSet(boolean value) {
    if (!value) {
      this.gender = null;
    }
  }

  public String getNationality() {
    return this.nationality;
  }

  public UserProfileResult setNationality(String nationality) {
    this.nationality = nationality;
    return this;
  }

  public void unsetNationality() {
    this.nationality = null;
  }

  /** Returns true if field nationality is set (has been assigned a value) and false otherwise */
  public boolean isSetNationality() {
    return this.nationality != null;
  }

  public void setNationalityIsSet(boolean value) {
    if (!value) {
      this.nationality = null;
    }
  }

  public String getTown() {
    return this.town;
  }

  public UserProfileResult setTown(String town) {
    this.town = town;
    return this;
  }

  public void unsetTown() {
    this.town = null;
  }

  /** Returns true if field town is set (has been assigned a value) and false otherwise */
  public boolean isSetTown() {
    return this.town != null;
  }

  public void setTownIsSet(boolean value) {
    if (!value) {
      this.town = null;
    }
  }

  public Politics247Generated.ThriftDate getDateOfBirth() {
    return this.dateOfBirth;
  }

  public UserProfileResult setDateOfBirth(Politics247Generated.ThriftDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

  public void unsetDateOfBirth() {
    this.dateOfBirth = null;
  }

  /** Returns true if field dateOfBirth is set (has been assigned a value) and false otherwise */
  public boolean isSetDateOfBirth() {
    return this.dateOfBirth != null;
  }

  public void setDateOfBirthIsSet(boolean value) {
    if (!value) {
      this.dateOfBirth = null;
    }
  }

  public String getPoliticalPreference() {
    return this.politicalPreference;
  }

  public UserProfileResult setPoliticalPreference(String politicalPreference) {
    this.politicalPreference = politicalPreference;
    return this;
  }

  public void unsetPoliticalPreference() {
    this.politicalPreference = null;
  }

  /** Returns true if field politicalPreference is set (has been assigned a value) and false otherwise */
  public boolean isSetPoliticalPreference() {
    return this.politicalPreference != null;
  }

  public void setPoliticalPreferenceIsSet(boolean value) {
    if (!value) {
      this.politicalPreference = null;
    }
  }

  /**
   * 
   * @see Politics247Generated.ThriftUserType
   */
  public Politics247Generated.ThriftUserType getType() {
    return this.type;
  }

  /**
   * 
   * @see Politics247Generated.ThriftUserType
   */
  public UserProfileResult setType(Politics247Generated.ThriftUserType type) {
    this.type = type;
    return this;
  }

  public void unsetType() {
    this.type = null;
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return this.type != null;
  }

  public void setTypeIsSet(boolean value) {
    if (!value) {
      this.type = null;
    }
  }

  public String getParty() {
    return this.party;
  }

  public UserProfileResult setParty(String party) {
    this.party = party;
    return this;
  }

  public void unsetParty() {
    this.party = null;
  }

  /** Returns true if field party is set (has been assigned a value) and false otherwise */
  public boolean isSetParty() {
    return this.party != null;
  }

  public void setPartyIsSet(boolean value) {
    if (!value) {
      this.party = null;
    }
  }

  public String getMedia() {
    return this.media;
  }

  public UserProfileResult setMedia(String media) {
    this.media = media;
    return this;
  }

  public void unsetMedia() {
    this.media = null;
  }

  /** Returns true if field media is set (has been assigned a value) and false otherwise */
  public boolean isSetMedia() {
    return this.media != null;
  }

  public void setMediaIsSet(boolean value) {
    if (!value) {
      this.media = null;
    }
  }

  public int getUserId() {
    return this.userId;
  }

  public UserProfileResult setUserId(int userId) {
    this.userId = userId;
    setUserIdIsSet(true);
    return this;
  }

  public void unsetUserId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  /** Returns true if field userId is set (has been assigned a value) and false otherwise */
  public boolean isSetUserId() {
    return EncodingUtils.testBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  public void setUserIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __USERID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case IS_USER_PROFILE_VALID:
      if (value == null) {
        unsetIsUserProfileValid();
      } else {
        setIsUserProfileValid((Boolean)value);
      }
      break;

    case FIRST_NAME:
      if (value == null) {
        unsetFirstName();
      } else {
        setFirstName((String)value);
      }
      break;

    case LAST_NAME:
      if (value == null) {
        unsetLastName();
      } else {
        setLastName((String)value);
      }
      break;

    case LAST_NAME_PREFIX:
      if (value == null) {
        unsetLastNamePrefix();
      } else {
        setLastNamePrefix((String)value);
      }
      break;

    case GENDER:
      if (value == null) {
        unsetGender();
      } else {
        setGender((Politics247Generated.ThriftGender)value);
      }
      break;

    case NATIONALITY:
      if (value == null) {
        unsetNationality();
      } else {
        setNationality((String)value);
      }
      break;

    case TOWN:
      if (value == null) {
        unsetTown();
      } else {
        setTown((String)value);
      }
      break;

    case DATE_OF_BIRTH:
      if (value == null) {
        unsetDateOfBirth();
      } else {
        setDateOfBirth((Politics247Generated.ThriftDate)value);
      }
      break;

    case POLITICAL_PREFERENCE:
      if (value == null) {
        unsetPoliticalPreference();
      } else {
        setPoliticalPreference((String)value);
      }
      break;

    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((Politics247Generated.ThriftUserType)value);
      }
      break;

    case PARTY:
      if (value == null) {
        unsetParty();
      } else {
        setParty((String)value);
      }
      break;

    case MEDIA:
      if (value == null) {
        unsetMedia();
      } else {
        setMedia((String)value);
      }
      break;

    case USER_ID:
      if (value == null) {
        unsetUserId();
      } else {
        setUserId((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case IS_USER_PROFILE_VALID:
      return isIsUserProfileValid();

    case FIRST_NAME:
      return getFirstName();

    case LAST_NAME:
      return getLastName();

    case LAST_NAME_PREFIX:
      return getLastNamePrefix();

    case GENDER:
      return getGender();

    case NATIONALITY:
      return getNationality();

    case TOWN:
      return getTown();

    case DATE_OF_BIRTH:
      return getDateOfBirth();

    case POLITICAL_PREFERENCE:
      return getPoliticalPreference();

    case TYPE:
      return getType();

    case PARTY:
      return getParty();

    case MEDIA:
      return getMedia();

    case USER_ID:
      return getUserId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case IS_USER_PROFILE_VALID:
      return isSetIsUserProfileValid();
    case FIRST_NAME:
      return isSetFirstName();
    case LAST_NAME:
      return isSetLastName();
    case LAST_NAME_PREFIX:
      return isSetLastNamePrefix();
    case GENDER:
      return isSetGender();
    case NATIONALITY:
      return isSetNationality();
    case TOWN:
      return isSetTown();
    case DATE_OF_BIRTH:
      return isSetDateOfBirth();
    case POLITICAL_PREFERENCE:
      return isSetPoliticalPreference();
    case TYPE:
      return isSetType();
    case PARTY:
      return isSetParty();
    case MEDIA:
      return isSetMedia();
    case USER_ID:
      return isSetUserId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UserProfileResult)
      return this.equals((UserProfileResult)that);
    return false;
  }

  public boolean equals(UserProfileResult that) {
    if (that == null)
      return false;

    boolean this_present_isUserProfileValid = true;
    boolean that_present_isUserProfileValid = true;
    if (this_present_isUserProfileValid || that_present_isUserProfileValid) {
      if (!(this_present_isUserProfileValid && that_present_isUserProfileValid))
        return false;
      if (this.isUserProfileValid != that.isUserProfileValid)
        return false;
    }

    boolean this_present_firstName = true && this.isSetFirstName();
    boolean that_present_firstName = true && that.isSetFirstName();
    if (this_present_firstName || that_present_firstName) {
      if (!(this_present_firstName && that_present_firstName))
        return false;
      if (!this.firstName.equals(that.firstName))
        return false;
    }

    boolean this_present_lastName = true && this.isSetLastName();
    boolean that_present_lastName = true && that.isSetLastName();
    if (this_present_lastName || that_present_lastName) {
      if (!(this_present_lastName && that_present_lastName))
        return false;
      if (!this.lastName.equals(that.lastName))
        return false;
    }

    boolean this_present_lastNamePrefix = true && this.isSetLastNamePrefix();
    boolean that_present_lastNamePrefix = true && that.isSetLastNamePrefix();
    if (this_present_lastNamePrefix || that_present_lastNamePrefix) {
      if (!(this_present_lastNamePrefix && that_present_lastNamePrefix))
        return false;
      if (!this.lastNamePrefix.equals(that.lastNamePrefix))
        return false;
    }

    boolean this_present_gender = true && this.isSetGender();
    boolean that_present_gender = true && that.isSetGender();
    if (this_present_gender || that_present_gender) {
      if (!(this_present_gender && that_present_gender))
        return false;
      if (!this.gender.equals(that.gender))
        return false;
    }

    boolean this_present_nationality = true && this.isSetNationality();
    boolean that_present_nationality = true && that.isSetNationality();
    if (this_present_nationality || that_present_nationality) {
      if (!(this_present_nationality && that_present_nationality))
        return false;
      if (!this.nationality.equals(that.nationality))
        return false;
    }

    boolean this_present_town = true && this.isSetTown();
    boolean that_present_town = true && that.isSetTown();
    if (this_present_town || that_present_town) {
      if (!(this_present_town && that_present_town))
        return false;
      if (!this.town.equals(that.town))
        return false;
    }

    boolean this_present_dateOfBirth = true && this.isSetDateOfBirth();
    boolean that_present_dateOfBirth = true && that.isSetDateOfBirth();
    if (this_present_dateOfBirth || that_present_dateOfBirth) {
      if (!(this_present_dateOfBirth && that_present_dateOfBirth))
        return false;
      if (!this.dateOfBirth.equals(that.dateOfBirth))
        return false;
    }

    boolean this_present_politicalPreference = true && this.isSetPoliticalPreference();
    boolean that_present_politicalPreference = true && that.isSetPoliticalPreference();
    if (this_present_politicalPreference || that_present_politicalPreference) {
      if (!(this_present_politicalPreference && that_present_politicalPreference))
        return false;
      if (!this.politicalPreference.equals(that.politicalPreference))
        return false;
    }

    boolean this_present_type = true && this.isSetType();
    boolean that_present_type = true && that.isSetType();
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (!this.type.equals(that.type))
        return false;
    }

    boolean this_present_party = true && this.isSetParty();
    boolean that_present_party = true && that.isSetParty();
    if (this_present_party || that_present_party) {
      if (!(this_present_party && that_present_party))
        return false;
      if (!this.party.equals(that.party))
        return false;
    }

    boolean this_present_media = true && this.isSetMedia();
    boolean that_present_media = true && that.isSetMedia();
    if (this_present_media || that_present_media) {
      if (!(this_present_media && that_present_media))
        return false;
      if (!this.media.equals(that.media))
        return false;
    }

    boolean this_present_userId = true;
    boolean that_present_userId = true;
    if (this_present_userId || that_present_userId) {
      if (!(this_present_userId && that_present_userId))
        return false;
      if (this.userId != that.userId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_isUserProfileValid = true;
    list.add(present_isUserProfileValid);
    if (present_isUserProfileValid)
      list.add(isUserProfileValid);

    boolean present_firstName = true && (isSetFirstName());
    list.add(present_firstName);
    if (present_firstName)
      list.add(firstName);

    boolean present_lastName = true && (isSetLastName());
    list.add(present_lastName);
    if (present_lastName)
      list.add(lastName);

    boolean present_lastNamePrefix = true && (isSetLastNamePrefix());
    list.add(present_lastNamePrefix);
    if (present_lastNamePrefix)
      list.add(lastNamePrefix);

    boolean present_gender = true && (isSetGender());
    list.add(present_gender);
    if (present_gender)
      list.add(gender.getValue());

    boolean present_nationality = true && (isSetNationality());
    list.add(present_nationality);
    if (present_nationality)
      list.add(nationality);

    boolean present_town = true && (isSetTown());
    list.add(present_town);
    if (present_town)
      list.add(town);

    boolean present_dateOfBirth = true && (isSetDateOfBirth());
    list.add(present_dateOfBirth);
    if (present_dateOfBirth)
      list.add(dateOfBirth);

    boolean present_politicalPreference = true && (isSetPoliticalPreference());
    list.add(present_politicalPreference);
    if (present_politicalPreference)
      list.add(politicalPreference);

    boolean present_type = true && (isSetType());
    list.add(present_type);
    if (present_type)
      list.add(type.getValue());

    boolean present_party = true && (isSetParty());
    list.add(present_party);
    if (present_party)
      list.add(party);

    boolean present_media = true && (isSetMedia());
    list.add(present_media);
    if (present_media)
      list.add(media);

    boolean present_userId = true;
    list.add(present_userId);
    if (present_userId)
      list.add(userId);

    return list.hashCode();
  }

  @Override
  public int compareTo(UserProfileResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetIsUserProfileValid()).compareTo(other.isSetIsUserProfileValid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsUserProfileValid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isUserProfileValid, other.isUserProfileValid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFirstName()).compareTo(other.isSetFirstName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFirstName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.firstName, other.firstName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastName()).compareTo(other.isSetLastName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastName, other.lastName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastNamePrefix()).compareTo(other.isSetLastNamePrefix());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastNamePrefix()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastNamePrefix, other.lastNamePrefix);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetGender()).compareTo(other.isSetGender());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGender()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gender, other.gender);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNationality()).compareTo(other.isSetNationality());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNationality()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nationality, other.nationality);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTown()).compareTo(other.isSetTown());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTown()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.town, other.town);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDateOfBirth()).compareTo(other.isSetDateOfBirth());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDateOfBirth()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dateOfBirth, other.dateOfBirth);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPoliticalPreference()).compareTo(other.isSetPoliticalPreference());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPoliticalPreference()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.politicalPreference, other.politicalPreference);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetType()).compareTo(other.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, other.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetParty()).compareTo(other.isSetParty());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParty()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.party, other.party);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMedia()).compareTo(other.isSetMedia());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMedia()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.media, other.media);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUserId()).compareTo(other.isSetUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userId, other.userId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UserProfileResult(");
    boolean first = true;

    sb.append("isUserProfileValid:");
    sb.append(this.isUserProfileValid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("firstName:");
    if (this.firstName == null) {
      sb.append("null");
    } else {
      sb.append(this.firstName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastName:");
    if (this.lastName == null) {
      sb.append("null");
    } else {
      sb.append(this.lastName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastNamePrefix:");
    if (this.lastNamePrefix == null) {
      sb.append("null");
    } else {
      sb.append(this.lastNamePrefix);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("gender:");
    if (this.gender == null) {
      sb.append("null");
    } else {
      sb.append(this.gender);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("nationality:");
    if (this.nationality == null) {
      sb.append("null");
    } else {
      sb.append(this.nationality);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("town:");
    if (this.town == null) {
      sb.append("null");
    } else {
      sb.append(this.town);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dateOfBirth:");
    if (this.dateOfBirth == null) {
      sb.append("null");
    } else {
      sb.append(this.dateOfBirth);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("politicalPreference:");
    if (this.politicalPreference == null) {
      sb.append("null");
    } else {
      sb.append(this.politicalPreference);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("type:");
    if (this.type == null) {
      sb.append("null");
    } else {
      sb.append(this.type);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("party:");
    if (this.party == null) {
      sb.append("null");
    } else {
      sb.append(this.party);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("media:");
    if (this.media == null) {
      sb.append("null");
    } else {
      sb.append(this.media);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("userId:");
    sb.append(this.userId);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (dateOfBirth != null) {
      dateOfBirth.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserProfileResultStandardSchemeFactory implements SchemeFactory {
    public UserProfileResultStandardScheme getScheme() {
      return new UserProfileResultStandardScheme();
    }
  }

  private static class UserProfileResultStandardScheme extends StandardScheme<UserProfileResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UserProfileResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IS_USER_PROFILE_VALID
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isUserProfileValid = iprot.readBool();
              struct.setIsUserProfileValidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FIRST_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.firstName = iprot.readString();
              struct.setFirstNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LAST_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.lastName = iprot.readString();
              struct.setLastNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LAST_NAME_PREFIX
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.lastNamePrefix = iprot.readString();
              struct.setLastNamePrefixIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // GENDER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.gender = Politics247Generated.ThriftGender.findByValue(iprot.readI32());
              struct.setGenderIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // NATIONALITY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.nationality = iprot.readString();
              struct.setNationalityIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // TOWN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.town = iprot.readString();
              struct.setTownIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // DATE_OF_BIRTH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.dateOfBirth = new Politics247Generated.ThriftDate();
              struct.dateOfBirth.read(iprot);
              struct.setDateOfBirthIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // POLITICAL_PREFERENCE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.politicalPreference = iprot.readString();
              struct.setPoliticalPreferenceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type = Politics247Generated.ThriftUserType.findByValue(iprot.readI32());
              struct.setTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // PARTY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.party = iprot.readString();
              struct.setPartyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // MEDIA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.media = iprot.readString();
              struct.setMediaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.userId = iprot.readI32();
              struct.setUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UserProfileResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(IS_USER_PROFILE_VALID_FIELD_DESC);
      oprot.writeBool(struct.isUserProfileValid);
      oprot.writeFieldEnd();
      if (struct.firstName != null) {
        oprot.writeFieldBegin(FIRST_NAME_FIELD_DESC);
        oprot.writeString(struct.firstName);
        oprot.writeFieldEnd();
      }
      if (struct.lastName != null) {
        oprot.writeFieldBegin(LAST_NAME_FIELD_DESC);
        oprot.writeString(struct.lastName);
        oprot.writeFieldEnd();
      }
      if (struct.lastNamePrefix != null) {
        oprot.writeFieldBegin(LAST_NAME_PREFIX_FIELD_DESC);
        oprot.writeString(struct.lastNamePrefix);
        oprot.writeFieldEnd();
      }
      if (struct.gender != null) {
        oprot.writeFieldBegin(GENDER_FIELD_DESC);
        oprot.writeI32(struct.gender.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.nationality != null) {
        oprot.writeFieldBegin(NATIONALITY_FIELD_DESC);
        oprot.writeString(struct.nationality);
        oprot.writeFieldEnd();
      }
      if (struct.town != null) {
        oprot.writeFieldBegin(TOWN_FIELD_DESC);
        oprot.writeString(struct.town);
        oprot.writeFieldEnd();
      }
      if (struct.dateOfBirth != null) {
        oprot.writeFieldBegin(DATE_OF_BIRTH_FIELD_DESC);
        struct.dateOfBirth.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.politicalPreference != null) {
        oprot.writeFieldBegin(POLITICAL_PREFERENCE_FIELD_DESC);
        oprot.writeString(struct.politicalPreference);
        oprot.writeFieldEnd();
      }
      if (struct.type != null) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeI32(struct.type.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.party != null) {
        oprot.writeFieldBegin(PARTY_FIELD_DESC);
        oprot.writeString(struct.party);
        oprot.writeFieldEnd();
      }
      if (struct.media != null) {
        oprot.writeFieldBegin(MEDIA_FIELD_DESC);
        oprot.writeString(struct.media);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(USER_ID_FIELD_DESC);
      oprot.writeI32(struct.userId);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserProfileResultTupleSchemeFactory implements SchemeFactory {
    public UserProfileResultTupleScheme getScheme() {
      return new UserProfileResultTupleScheme();
    }
  }

  private static class UserProfileResultTupleScheme extends TupleScheme<UserProfileResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UserProfileResult struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetIsUserProfileValid()) {
        optionals.set(0);
      }
      if (struct.isSetFirstName()) {
        optionals.set(1);
      }
      if (struct.isSetLastName()) {
        optionals.set(2);
      }
      if (struct.isSetLastNamePrefix()) {
        optionals.set(3);
      }
      if (struct.isSetGender()) {
        optionals.set(4);
      }
      if (struct.isSetNationality()) {
        optionals.set(5);
      }
      if (struct.isSetTown()) {
        optionals.set(6);
      }
      if (struct.isSetDateOfBirth()) {
        optionals.set(7);
      }
      if (struct.isSetPoliticalPreference()) {
        optionals.set(8);
      }
      if (struct.isSetType()) {
        optionals.set(9);
      }
      if (struct.isSetParty()) {
        optionals.set(10);
      }
      if (struct.isSetMedia()) {
        optionals.set(11);
      }
      if (struct.isSetUserId()) {
        optionals.set(12);
      }
      oprot.writeBitSet(optionals, 13);
      if (struct.isSetIsUserProfileValid()) {
        oprot.writeBool(struct.isUserProfileValid);
      }
      if (struct.isSetFirstName()) {
        oprot.writeString(struct.firstName);
      }
      if (struct.isSetLastName()) {
        oprot.writeString(struct.lastName);
      }
      if (struct.isSetLastNamePrefix()) {
        oprot.writeString(struct.lastNamePrefix);
      }
      if (struct.isSetGender()) {
        oprot.writeI32(struct.gender.getValue());
      }
      if (struct.isSetNationality()) {
        oprot.writeString(struct.nationality);
      }
      if (struct.isSetTown()) {
        oprot.writeString(struct.town);
      }
      if (struct.isSetDateOfBirth()) {
        struct.dateOfBirth.write(oprot);
      }
      if (struct.isSetPoliticalPreference()) {
        oprot.writeString(struct.politicalPreference);
      }
      if (struct.isSetType()) {
        oprot.writeI32(struct.type.getValue());
      }
      if (struct.isSetParty()) {
        oprot.writeString(struct.party);
      }
      if (struct.isSetMedia()) {
        oprot.writeString(struct.media);
      }
      if (struct.isSetUserId()) {
        oprot.writeI32(struct.userId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UserProfileResult struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(13);
      if (incoming.get(0)) {
        struct.isUserProfileValid = iprot.readBool();
        struct.setIsUserProfileValidIsSet(true);
      }
      if (incoming.get(1)) {
        struct.firstName = iprot.readString();
        struct.setFirstNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.lastName = iprot.readString();
        struct.setLastNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.lastNamePrefix = iprot.readString();
        struct.setLastNamePrefixIsSet(true);
      }
      if (incoming.get(4)) {
        struct.gender = Politics247Generated.ThriftGender.findByValue(iprot.readI32());
        struct.setGenderIsSet(true);
      }
      if (incoming.get(5)) {
        struct.nationality = iprot.readString();
        struct.setNationalityIsSet(true);
      }
      if (incoming.get(6)) {
        struct.town = iprot.readString();
        struct.setTownIsSet(true);
      }
      if (incoming.get(7)) {
        struct.dateOfBirth = new Politics247Generated.ThriftDate();
        struct.dateOfBirth.read(iprot);
        struct.setDateOfBirthIsSet(true);
      }
      if (incoming.get(8)) {
        struct.politicalPreference = iprot.readString();
        struct.setPoliticalPreferenceIsSet(true);
      }
      if (incoming.get(9)) {
        struct.type = Politics247Generated.ThriftUserType.findByValue(iprot.readI32());
        struct.setTypeIsSet(true);
      }
      if (incoming.get(10)) {
        struct.party = iprot.readString();
        struct.setPartyIsSet(true);
      }
      if (incoming.get(11)) {
        struct.media = iprot.readString();
        struct.setMediaIsSet(true);
      }
      if (incoming.get(12)) {
        struct.userId = iprot.readI32();
        struct.setUserIdIsSet(true);
      }
    }
  }

}

